spring:
  profiles:
    active: local
server:
  port: 8082

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    template:
      default-topic: book-events
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: book-events-listener-group
    producer:
      bootstrap-servers:
        -   localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
amazon:
  access:
    key: teste123
    secret-key: teste123
  region: eu-west-1
  end-point:
    url: http://localhost:8000


---

spring:
  config:
    activate:
      on-profile: nonprod
  kafka:
    template:
      default-topic: book-events
    consumer:
      bootstrap-servers: localhost:9095
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: book-events-listener-group
      ssl:
        trust-store-location: file:/home/idd_rsouza/Documentos/JavaTrainee/POCv1/learn-kafka/ssl/client.truststore.jks
        trust-store-password: password
        key-store-location: file:/home/idd_rsouza/Documentos/JavaTrainee/POCv1/learn-kafka/ssl/client.keystore.jks
        key-store-password: password
    producer:
      bootstrap-servers:
        -   localhost:9095
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      security:
        protocol: SSL
      ssl.endpoint.identification.algorithm:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: prod
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-group